- name: Install Java
  yum:
    name: "java-1.8.0-openjdk"
    state: latest
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
- file:
    path: /var/private/ssl
    state: directory
    mode: 0755
- template:
    src: test.j2
    dest: /var/private/ssl/test.sh
    owner: root
    group: root
    mode: 0777
- command: bash test.sh
  args:
    chdir: /var/private/ssl/
